Metrics/LineLength:
  Max: 102
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Style/FileName:
  Enabled: false
